import styles from './layout.module.css';
import Head from 'next/head';

export default function Layout({ children }) {
    return(
    <div className={styles.container}>
        <Head>
        <title>ED3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.header}>Elastic Dummy 003</h1>
        <main>{children}</main>
    </div>
    );
}