import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Popup from '../components/Popup';

import { useState } from 'react';

export default function Home() {

  const [popupToggle, setPopupToggle] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>ED3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://mariosan.com/elasticdummy003" target="_blank" rel="noopener noreferrer">ED-003</a>
        </h1>
        <p className={styles.description}>
          A web-based granular synthesizer<br/>with a React Three Fiber based UI.<br/>Works better with headphones.
        </p>
        <Link href='/screen'>
          <a className={styles.headingMd}>Click here to continue.</a>
        </Link>
      </main>
      { popupToggle ? <Popup togglePopup={() => {setPopupToggle(!popupToggle)}}/> : <></> }
      <Footer togglePopup={() => {setPopupToggle(!popupToggle)}}/>
    </div>
  )
}
