import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ED3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">ED-003</a>
        </h1>
        <p className={styles.description}>
          A web-based granular synthesizer with a Three.js based UI. Works better with headphones.
        </p>
        <Link href='/screen'>
          <a className={styles.headingMd}>Press here to continue.</a>
        </Link>
      </main>
    </div>
  )
}
